apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo
  namespace: default
spec:
  selector:
    matchLabels:
      app: jenkins-demo
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      containers:
      - image: swr.cn-south-1.myhuaweicloud.com/xlink-e3-sit/jenkins-demo:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        command:
          - sleep
        args:
          - '1000'
        name: jenkins-demo
        env:
        - name: branch
      imagePullSecrets:
        - name: default-secret
